# Generated by Django 3.0.3 on 2020-05-14 13:27

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner1', models.CharField(max_length=60)),
                ('partner2', models.CharField(max_length=60)),
                ('hall_name', models.CharField(max_length=60)),
                ('event_address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=60)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_health.Event')),
            ],
        ),
    ]
