# Generated by Django 3.0.3 on 2020-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_address',
            new_name='event_location',
        ),
        migrations.AddField(
            model_name='event',
            name='img1',
            field=models.URLField(default='https://pasteboard.co/J8me40J.jpg'),
        ),
        migrations.AddField(
            model_name='event',
            name='img2',
            field=models.URLField(default='https://pasteboard.co/J8me40J.jpg'),
        ),
        migrations.AddField(
            model_name='event',
            name='img3',
            field=models.URLField(default='https://pasteboard.co/J8me40J.jpg'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_id',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
