# Generated by Django 3.0.3 on 2020-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0002_auto_20200514_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img1',
            field=models.URLField(default='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-1181856013.jpg'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img2',
            field=models.URLField(default='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-1181856013.jpg'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img3',
            field=models.URLField(default='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-1181856013.jpg'),
        ),
    ]
