# Generated by Django 3.0.3 on 2020-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0003_auto_20200514_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-06-14'),
        ),
    ]
