# Generated by Django 3.0.3 on 2020-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0005_auto_20200514_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='11/12/20'),
        ),
    ]
