# Generated by Django 3.0.3 on 2020-05-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0008_auto_20200514_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-06-14'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events_health.Event'),
        ),
    ]
