# Generated by Django 3.0.3 on 2020-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0010_auto_20200515_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
