# Generated by Django 3.0.3 on 2020-05-19 11:14

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('events_health', '0011_auto_20200518_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='SMS_count',
            field=models.PositiveIntegerField(default=0, verbose_name='מספר הודעות שנשלחו'),
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[(0, 'לא רשום'), (1, 'רשום')], default=(0, 'לא רשום'), max_length=60, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.PositiveIntegerField(verbose_name='גיל'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_health.Event', verbose_name='אירוע'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=60, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='מספר טלפון'),
        ),
    ]
