# Generated by Django 3.0.3 on 2020-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_health', '0013_auto_20200519_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[(0, 'לא רשום'), (1, 'רשום')], default=0, max_length=60, verbose_name='סטטוס'),
        ),
    ]
