# Generated by Django 3.0.3 on 2020-05-06 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sender_name', models.CharField(max_length=60)),
                ('sender_email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('notifications_email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('unsubscribed', models.IntegerField(default=0)),
                ('sum_sent', models.IntegerField(default=0)),
                ('sum_confirm', models.IntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('unsubscribe', models.BooleanField(default=0)),
                ('url_id', models.CharField(blank=True, default='', max_length=7)),
                ('sent', models.CharField(max_length=10)),
                ('opend', models.CharField(max_length=10)),
                ('next_email_index', models.CharField(max_length=10)),
                ('send_email_date', models.DateField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('html', models.CharField(max_length=60)),
                ('delay_H', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(1, 'on'), (0, 'of')], default=0, max_length=2)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Campaign')),
            ],
        ),
    ]
