# Generated by Django 3.0.3 on 2020-05-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='opend',
            new_name='opened',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='next_email_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Email'),
        ),
    ]
