# Generated by Django 3.0.3 on 2020-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200506_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
